<?php
/**
 * This file is part of KrscReports.
 *
 * Copyright (c) 2016 Krzysztof Ruszczyński
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
 *
 * @category KrscReports
 * @package KrscReports_Report
 * @copyright Copyright (c) 2016 Krzysztof Ruszczyński
 * @license http://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt	LGPL
 * @version 1.0.2, 2016-11-13
 */

/**
 * Example report creating two tables in different worksheets with borders and fillment (difference in style between header and rows) in PHPExcel. 
 * 
 * @category KrscReports
 * @package KrscReports_Report
 * @author Krzysztof Ruszczyński <http://www.ruszczynski.eu>
 */
class KrscReports_Report_ExampleReportDifferentStyles extends KrscReports_Report_ExampleReport
{
    /**
     * key style with light blue fill
     */
    const STYLE_ROW_DARK_GREEN = 'style_dark_green';
    
    /**
     * hex style with dark yellow fill
     */
    const STYLE_ROW_DARK_YELLOW = 'style_dark_yellow';
    
    /**
     * key style with orange fill
     */
    const STYLE_ROW_ORANGE = 'style_orange';
    
    /**
     * key style with red fill
     */
    const STYLE_ROW_RED = 'style_row_red';
    
    /**
     * Method returns description of generated by that object worksheet.
     * @return string description of report
     */
    public function getDescription()
    {
        return 'Report with one table with color of fillment varying from row to row.';
    }

    /**
     * Method responsible for creating PHPExcel object with generated report.
     * @return void
     */
    public function generate()
    {
        // setting styles - adding elements to iterator 
        $oCollectionDefault = new KrscReports_Type_Excel_PHPExcel_Style_Iterator_Collection();
        $oCollectionDefault->addStyleElement( new KrscReports_Type_Excel_PHPExcel_Style_Borders_ExampleBorders() );
        
        $oCollectionRowLightGreen = new KrscReports_Type_Excel_PHPExcel_Style_Iterator_Collection();
        $oCollectionRowLightGreen->addStyleElement( new KrscReports_Type_Excel_PHPExcel_Style_Fill_ExampleFill() );
        $oCollectionRowLightGreen->addStyleElement( new KrscReports_Type_Excel_PHPExcel_Style_Borders_DashDotDotBorders() );
        
        $oFillDarkYellow = new KrscReports_Type_Excel_PHPExcel_Style_Fill_ExampleFill();
        $oFillDarkYellow->setFillColor( KrscReports_Type_Excel_PHPExcel_Style_Fill_ExampleFill::COLOR_DARK_YELLOW );
        $oCollectionDarkYellow = new KrscReports_Type_Excel_PHPExcel_Style_Iterator_Collection();
        $oCollectionDarkYellow->addStyleElement( $oFillDarkYellow );
        $oCollectionDarkYellow->addStyleElement( new KrscReports_Type_Excel_PHPExcel_Style_Borders_DashDotDotBorders() );
        
        $oFillRed = new KrscReports_Type_Excel_PHPExcel_Style_Fill_ExampleFill();
        $oFillRed->setFillColor( KrscReports_Type_Excel_PHPExcel_Style_Fill_ExampleFill::COLOR_RED );
        $oCollectionRowRed = new KrscReports_Type_Excel_PHPExcel_Style_Iterator_Collection();
        $oCollectionRowRed->addStyleElement( $oFillRed );
        $oCollectionRowRed->addStyleElement( new KrscReports_Type_Excel_PHPExcel_Style_Borders_DashDotDotBorders() );
        
        $oFillDarkGreen = new KrscReports_Type_Excel_PHPExcel_Style_Fill_ExampleFill();
        $oFillDarkGreen->setFillColor( KrscReports_Type_Excel_PHPExcel_Style_Fill_ExampleFill::COLOR_DARK_GREEN );
        $oCollectionDarkGreen = new KrscReports_Type_Excel_PHPExcel_Style_Iterator_Collection();
        $oCollectionDarkGreen->addStyleElement( $oFillDarkGreen );
        $oCollectionDarkGreen->addStyleElement( new KrscReports_Type_Excel_PHPExcel_Style_Borders_DashDotDotBorders() );
        
        $oFillOrange = new KrscReports_Type_Excel_PHPExcel_Style_Fill_ExampleFill();
        $oFillOrange->setFillColor( KrscReports_Type_Excel_PHPExcel_Style_Fill_ExampleFill::COLOR_ORANGE );
        $oCollectionOrange = new KrscReports_Type_Excel_PHPExcel_Style_Iterator_Collection();
        $oCollectionOrange->addStyleElement( $oFillOrange );
        $oCollectionOrange->addStyleElement( new KrscReports_Type_Excel_PHPExcel_Style_Borders_DashDotDotBorders() );
        
        $oStyle = new KrscReports_Type_Excel_PHPExcel_Style();
        $oStyle->setStyleCollection( $oCollectionDefault );
        $oStyle->setStyleCollection( $oCollectionRowLightGreen, KrscReports_Document_Element_Table::STYLE_ROW );
        $oStyle->setStyleCollection( $oCollectionDarkYellow, self::STYLE_ROW_DARK_YELLOW );
        $oStyle->setStyleCollection( $oCollectionRowRed, self::STYLE_ROW_RED );
        $oStyle->setStyleCollection( $oCollectionDarkGreen, self::STYLE_ROW_DARK_GREEN );
        $oStyle->setStyleCollection( $oCollectionOrange, self::STYLE_ROW_ORANGE );
        
        KrscReports_Builder_Excel_PHPExcel::setPHPExcelObject( new PHPExcel() );
        $oCell = new KrscReports_Type_Excel_PHPExcel_Cell();
        $oCell->setStyleObject( $oStyle );
        
        $oBuilder = new KrscReports_Builder_Excel_PHPExcel_TableDifferentStyles();
        $oBuilder->setCellObject( $oCell );
        $oBuilder->setData( 
            array( 
                array( 'Place' => 'New York City', 'Height above sea level' => '12 m', KrscReports_Builder_Excel_PHPExcel_TableDifferentStyles::DATA_STYLE_COLUMN => self::STYLE_ROW_DARK_GREEN ), 
                array( 'Place' => 'Mount Strzelecki', 'Height above sea level' => '756 m', KrscReports_Builder_Excel_PHPExcel_TableDifferentStyles::DATA_STYLE_COLUMN => self::STYLE_ROW_DARK_YELLOW ),
                array( 'Place' => 'Mount Kosciuszko', 'Height above sea level' => '2228 m', KrscReports_Builder_Excel_PHPExcel_TableDifferentStyles::DATA_STYLE_COLUMN => self::STYLE_ROW_ORANGE ),
                array( 'Place' => 'Mount Everest', 'Height above sea level' => '8848 m', KrscReports_Builder_Excel_PHPExcel_TableDifferentStyles::DATA_STYLE_COLUMN => self::STYLE_ROW_RED )
            ) 
        );
        
        // creation of element responsible for creating table
        $oElementTable = new KrscReports_Document_Element_Table();
        $oElementTable->setBuilder( $oBuilder );
        
        // adding table to spreadsheet
        $oElement = new KrscReports_Document_Element();
        $oElement->addElement( $oElementTable );
        
        $oElement->beforeConstructDocument();
        $oElement->constructDocument();
        $oElement->afterConstructDocument();    
    }
}


