<?php
/**
 * This file is part of KrscReports.
 *
 * Copyright (c) 2014 Krzysztof Ruszczyński
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
 *
 * @category KrscReports
 * @package KrscReports_Report
 * @copyright Copyright (c) 2014 Krzysztof Ruszczyński
 * @license http://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt	LGPL
 * @version 1.0.0, 2014-12-28
 */

/**
 * Example report creating four tables in one worksheet with advanced styling in PHPExcel.
 * Start height and width for each table is set manually (for some only one parameter).
 * 
 * @category KrscReports
 * @package KrscReports_Report
 * @author Krzysztof Ruszczyński <http://www.ruszczynski.eu>
 */
class KrscReports_Report_ExampleReportVariousPlaces extends KrscReports_Report_ExampleReport
{
    /**
     * Method returns description of generated by that object worksheet.
     * @return string description of report
     */
    public function getDescription()
    {
        return 'Report with four tables in one worksheet with advanced styling. Start height and width for each table is set manually (for some only one parameter).';
    }
    
    /**
     * Method responsible for creating PHPExcel object with generated report.
     * @return void
     */
    public function generate()
    {
        // setting styles - adding elements to iterator 
        $oCollectionDefault = new KrscReports_Type_Excel_PHPExcel_Style_Iterator_Collection();
        $oCollectionDefault->addStyleElement( new KrscReports_Type_Excel_PHPExcel_Style_Borders_ExampleBorders() );
        
        $oCollectionRow = new KrscReports_Type_Excel_PHPExcel_Style_Iterator_Collection();
        $oCollectionRow->addStyleElement( new KrscReports_Type_Excel_PHPExcel_Style_Fill_ExampleFill() );
        $oCollectionRow->addStyleElement( new KrscReports_Type_Excel_PHPExcel_Style_Borders_DashDotDotBorders() );
        
        $oStyle = new KrscReports_Type_Excel_PHPExcel_Style();
        $oStyle->setStyleCollection( $oCollectionDefault );
        $oStyle->setStyleCollection( $oCollectionRow, KrscReports_Document_Element_Table::STYLE_ROW );
        
        //die( var_dump( $oStyle->getStyleArray( KrscReports_Document_Element_Table::STYLE_ROW ) ) );
        KrscReports_Builder_Excel_PHPExcel::setPHPExcelObject( new PHPExcel() );
        $oCell = new KrscReports_Type_Excel_PHPExcel_Cell();
        $oCell->setStyleObject( $oStyle );
        
        $oBuilder = new KrscReports_Builder_Excel_PHPExcel_ExampleTable();
        $oBuilder->setCellObject( $oCell );
        $oBuilder->setData( array( array( 'First column' => '1', 'Second column' => '2' ), array( 'First column' => '3', 'Second column' => '4' ) ) );
        
        // creation of element responsible for creating table
        $oElementTable = new KrscReports_Document_Element_Table();
        $oElementTable->setBuilder( $oBuilder );
        $oElementTable->setStartWidth(1);
        
        $oBuilder2 = new KrscReports_Builder_Excel_PHPExcel_ExampleTable();
        $oBuilder2->setCellObject( $oCell );
        $oBuilder2->setData( array( array( 'I column' => '5', 'II column' => '6' ), array( 'First column' => '7', 'Second column' => '8' ) ) );
        
        
        $oElementTable2 = new KrscReports_Document_Element_Table();
        $oElementTable2->setBuilder( $oBuilder2 );
        $oElementTable2->setStartWidth( 3 );
        $oElementTable2->setStartHeight( 15 );
        
        $oBuilder3 = new KrscReports_Builder_Excel_PHPExcel_ExampleTable();
        $oBuilder3->setCellObject( $oCell );
        $oBuilder3->setData( array( array( 'I column' => '55', 'II column' => '66' ), array( 'First column' => '77', 'Second column' => '88' ) ) );
                
        $oElementTable3 = new KrscReports_Document_Element_Table();
        $oElementTable3->setBuilder( $oBuilder3 );
        $oElementTable3->setStartWidth( 6 );
        $oElementTable3->setStartHeight( 14 );
        
        
        $oBuilder4 = new KrscReports_Builder_Excel_PHPExcel_ExampleTable();
        $oBuilder4->setCellObject( $oCell );
        $oBuilder4->setData( array( array( 'I column' => '155', 'II column' => '166' ), array( 'First column' => '177', 'Second column' => '188' ) ) );
                
        $oElementTable4 = new KrscReports_Document_Element_Table();
        $oElementTable4->setBuilder( $oBuilder4 );
        
        // adding table to spreadsheet
        $oElement = new KrscReports_Document_Element();
        $oElement->addElement( $oElementTable );
        $oElement->addElement( $oElementTable2 );
        $oElement->addElement( $oElementTable3 );
        $oElement->addElement( $oElementTable4 );
                
                
        $oElement->beforeConstructDocument();
        $oElement->constructDocument();
        $oElement->afterConstructDocument();
            
    }
}
