<?php
use KrscReports\Import\ReaderTrait;

/**
 * This file is part of KrscReports.
 *
 * Copyright (c) 2020 Krzysztof Ruszczyński
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
 *
 * @category KrscReports
 * @package KrscReports_Report
 * @copyright Copyright (c) 2020 Krzysztof Ruszczyński
 * @license http://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt	LGPL
 * @version 2.0.6, 2020-02-02
 */

/**
 * Example report creating one table with different row's styles in PHPExcel. 
 * 
 * @category KrscReports
 * @package KrscReports_Report
 * @author Krzysztof Ruszczyński <http://www.ruszczynski.eu>
 */
class KrscReports_Report_ExampleReportDifferentStyles extends KrscReports_Report_ExampleReport
{
    /**
     * key style with dark green fill
     */
    const STYLE_ROW_DARK_GREEN = 'style_dark_green';
    
    /**
     * key style with dark yellow fill
     */
    const STYLE_ROW_YELLOW = 'style_dark_yellow';
    
    /**
     * key style with orange fill
     */
    const STYLE_ROW_ORANGE = 'style_orange';
    
    /**
     * key style for gradient fill (from orange to red)
     */
    const STYLE_ROW_ORANGE_TO_RED = 'style_orange_to_red';
    
    /**
     * key style with red fill
     */
    const STYLE_ROW_RED = 'style_row_red';
    
    /**
     * Method returns description of generated by that object worksheet.
     * @return string description of report
     */
    public function getDescription()
    {
        return 'Report with one table with color of fillment varying from row to row.';
    }

    /**
     * Method responsible for creating PHPExcel object with generated report.
     * @return void
     */
    public function generate()
    {
        KrscReports_Builder_Excel::setExcelObject();
        $oCell = ReaderTrait::getCellObject();
        KrscReports_Builder_Excel::setDocumentProperties();

        // setting styles - adding elements to iterator 
        $oCollectionDefault = new KrscReports_Type_Excel_PHPExcel_Style_Iterator_Collection();
        $oCollectionDefault->addStyleElement( new KrscReports_Type_Excel_PHPExcel_Style_Borders_ExampleBorders() );
        
        $oCollectionRowLightGreen = new KrscReports_Type_Excel_PHPExcel_Style_Iterator_Collection();
        $oCollectionRowLightGreen->addStyleElement( new KrscReports_Type_Excel_PHPExcel_Style_Fill_Basic() );
        $oCollectionRowLightGreen->addStyleElement( new KrscReports_Type_Excel_PHPExcel_Style_Borders_DashDotDotBorders() );
        
        $oFillYellow = new KrscReports_Type_Excel_PHPExcel_Style_Fill_Basic();
        $oFillYellow->setColor( PHPExcel_Style_Color::COLOR_YELLOW );
        $oCollectionYellow = new KrscReports_Type_Excel_PHPExcel_Style_Iterator_Collection();
        $oCollectionYellow->addStyleElement( $oFillYellow );
        $oCollectionYellow->addStyleElement( new KrscReports_Type_Excel_PHPExcel_Style_Borders_DashDotDotBorders() );
        
        $oFillRed = new KrscReports_Type_Excel_PHPExcel_Style_Fill_Basic();
        $oFillRed->setColor( PHPExcel_Style_Color::COLOR_RED );
        $oCollectionRowRed = new KrscReports_Type_Excel_PHPExcel_Style_Iterator_Collection();
        $oCollectionRowRed->addStyleElement( $oFillRed );
        $oCollectionRowRed->addStyleElement( new KrscReports_Type_Excel_PHPExcel_Style_Borders_DashDotDotBorders() );
        
        $oFillDarkGreen = new KrscReports_Type_Excel_PHPExcel_Style_Fill_Basic();
        $oFillDarkGreen->setColor( PHPExcel_Style_Color::COLOR_DARKGREEN );
        $oCollectionDarkGreen = new KrscReports_Type_Excel_PHPExcel_Style_Iterator_Collection();
        $oCollectionDarkGreen->addStyleElement( $oFillDarkGreen );
        $oCollectionDarkGreen->addStyleElement( new KrscReports_Type_Excel_PHPExcel_Style_Borders_DashDotDotBorders() );
        
        $oFillOrange = new KrscReports_Type_Excel_PHPExcel_Style_Fill_Basic();
        $oFillOrange->setColor( KrscReports_Type_Excel_PHPExcel_Style_Default::COLOR_ORANGE );
        $oCollectionOrange = new KrscReports_Type_Excel_PHPExcel_Style_Iterator_Collection();
        $oCollectionOrange->addStyleElement( $oFillOrange );
        $oCollectionOrange->addStyleElement( new KrscReports_Type_Excel_PHPExcel_Style_Borders_DashDotDotBorders() );
        
        $oFillOrangeToRed = new KrscReports_Type_Excel_PHPExcel_Style_Fill_Basic();
        $oFillOrangeToRed->setStartColor( KrscReports_Type_Excel_PHPExcel_Style_Default::COLOR_ORANGE );
        $oFillOrangeToRed->setEndColor( PHPExcel_Style_Color::COLOR_RED );
        $oFillOrangeToRed->setType( PHPExcel_Style_Fill::FILL_PATTERN_LIGHTVERTICAL );
        $oFillOrangeToRed->setRotation( 45 );
        $oCollectionOrangeToRed = new KrscReports_Type_Excel_PHPExcel_Style_Iterator_Collection();
        $oCollectionOrangeToRed->addStyleElement( $oFillOrangeToRed );
        $oCollectionOrangeToRed->addStyleElement( new KrscReports_Type_Excel_PHPExcel_Style_Borders_DashDotDotBorders() );
        
        $oStyle = new KrscReports_Type_Excel_PHPExcel_Style();
        $oStyle->setStyleCollection( $oCollectionDefault );
        $oStyle->setStyleCollection( $oCollectionRowLightGreen, KrscReports_Document_Element_Table::STYLE_ROW );
        $oStyle->setStyleCollection( $oCollectionYellow, self::STYLE_ROW_YELLOW );
        $oStyle->setStyleCollection( $oCollectionRowRed, self::STYLE_ROW_RED );
        $oStyle->setStyleCollection( $oCollectionDarkGreen, self::STYLE_ROW_DARK_GREEN );
        $oStyle->setStyleCollection( $oCollectionOrange, self::STYLE_ROW_ORANGE );
        $oStyle->setStyleCollection( $oCollectionOrangeToRed, self::STYLE_ROW_ORANGE_TO_RED );

        $oCell->setStyleObject( $oStyle );

        $oBuilder = new KrscReports_Builder_Excel_PHPExcel_TableDifferentStyles();
        $oBuilder->setCellObject( $oCell );
        $oBuilder->setData( 
            array( 
                array( 'Place' => 'New York City', 'Height above sea level' => '12 m', KrscReports_Builder_Excel_PHPExcel_TableDifferentStyles::DATA_STYLE_COLUMN => self::STYLE_ROW_DARK_GREEN ), 
                array( 'Place' => 'Mount Strzelecki', 'Height above sea level' => '756 m', KrscReports_Builder_Excel_PHPExcel_TableDifferentStyles::DATA_STYLE_COLUMN => self::STYLE_ROW_YELLOW ),
                array( 'Place' => 'Mount Kosciuszko', 'Height above sea level' => '2228 m', KrscReports_Builder_Excel_PHPExcel_TableDifferentStyles::DATA_STYLE_COLUMN => self::STYLE_ROW_ORANGE ),
                array( 'Place' => 'Mount Kilimanjaro', 'Height above sea level' => '5895 m', KrscReports_Builder_Excel_PHPExcel_TableDifferentStyles::DATA_STYLE_COLUMN => self::STYLE_ROW_ORANGE_TO_RED ),
                array( 'Place' => 'Mount Everest', 'Height above sea level' => '8848 m', KrscReports_Builder_Excel_PHPExcel_TableDifferentStyles::DATA_STYLE_COLUMN => self::STYLE_ROW_RED )
            ) 
        );
        
        // creation of element responsible for creating table
        $oElementTable = new KrscReports_Document_Element_Table();
        $oElementTable->setBuilder( $oBuilder );
        
        // adding table to spreadsheet
        $oElement = new KrscReports_Document_Element();
        $oElement->addElement( $oElementTable );
        
        $oElement->beforeConstructDocument();
        $oElement->constructDocument();
        $oElement->afterConstructDocument();    
    }
}
