<?php
namespace KrscReports\Report;

use KrscReports\Service;
use KrscReports\Type\Excel\PhpSpreadsheet\StyleConstantsTranslatorTrait;
use KrscReports\Views\AbstractView;
use KrscReports\Views\SingleTableWithGraphs;

/**
 * This file is part of KrscReports.
 *
 * Copyright (c) 2020 Krzysztof Ruszczyński
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
 *
 * @category KrscReports
 * @package KrscReports_Report
 * @copyright Copyright (c) 2020 Krzysztof Ruszczyński
 * @license http://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt	LGPL
 * @version 2.0.6, 2020-02-23
 */

/**
 * Example report creating table with graph via Service.
 *
 * @category KrscReports
 * @package KrscReports_Report
 * @author Krzysztof Ruszczyński <http://www.ruszczynski.eu>
 */
class ExampleReportTableWithGraph extends \KrscReports_Report_ExampleReport implements ReportWithServiceInterface
{
    use StyleConstantsTranslatorTrait;

    /**
     * Method returns description of generated by that object worksheet.
     *
     * @return string description of report
     */
    public function getDescription()
    {
        return 'Report with one table with graph (made with \KrscReports\Service).';
    }

    /**
     * Method returning data for report.
     *
     * @return array
     */
    public function getReportData()
    {
        return array(
            array('2020-01-01', '1.4'),
            array('2020-01-02', '1.1'),
            array('2020-01-03', '0.2'),
            array('2020-01-04', '3.7'),
            array('2020-01-05', '0.6'),
            array('2020-01-06', '-0.1'),
            array('2020-01-07', '1.0'),
            array('2020-01-08', '3.3'),
            array('2020-01-09', '5.8'),
            array('2020-01-10', '7.2'),
            array('2020-01-11', '5.6'),
            array('2020-01-12', '3.5'),
            array('2020-01-13', '4.7'),
            array('2020-01-14', '3.4'),
            array('2020-01-15', '4.7'),
            array('2020-01-16', '3.8'),
            array('2020-01-17', '-0.5'),
            array('2020-01-18', '2.7'),
            array('2020-01-19', '2.8'),
            array('2020-01-20', '2.0'),
            array('2020-01-21', '2.3'),
            array('2020-01-22', '2.6'),
            array('2020-01-23', '0.8'),
            array('2020-01-24', '1.2'),
            array('2020-01-25', '0.5'),
            array('2020-01-26', '-0.1'),
            array('2020-01-27', '0.7'),
            array('2020-01-28', '1.5'),
            array('2020-01-29', '2.3'),
            array('2020-01-30', '3.2'),
            array('2020-01-31', '6.3'),
        );
    }

    /**
     * Method returning prepared view.
     *
     * @return \KrscReports\Views\AbstractView
     */
    public function getReportView()
    {
        $aColumns = array('Date', 'Avg. temperature');

        $oReportView = new SingleTableWithGraphs();
        $oReportView->addOptions(
            array(
                AbstractView::KEY_DOCUMENT_PROPERTIES => array(),
                AbstractView::KEY_USE_FROM_ARRAY => true,
                SingleTableWithGraphs::KEY_GRAPHS =>
                    array(
                        array(
                            SingleTableWithGraphs::KEY_GRAPHS_PLOT_TYPE =>
                                $this->getTranslatedStyleConstant('PHPExcel_Chart_DataSeries', 'TYPE_LINECHART'),
                            SingleTableWithGraphs::KEY_GRAPHS_COLUMN_CATEGORY => 'Date',
                            SingleTableWithGraphs::KEY_GRAPHS_COLUMN_VALUES => 'Avg. temperature',
                            SingleTableWithGraphs::KEY_GRAPHS_COLUMN_SIZE => 16,
                            SingleTableWithGraphs::KEY_GRAPHS_ROW_SIZE => 20,
                            SingleTableWithGraphs::KEY_GRAPHS_ROWS_OFFSET => 0,
                            SingleTableWithGraphs::KEY_GRAPHS_TITLE =>
                                'Average temperature in Warsaw (PL) - January 2020',
                        )
                    )
            )
        );

        $oReportView->setData(
            $this->getReportData(),
            $aColumns
        );

        return $oReportView;
    }

    /**
     * Method responsible for creating service with generated report.
     *
     * @return void
     */
    public function generate()
    {
        $oExcelService = new Service();
        $oExcelService->setSpreadsheetName('First_Spreadsheet');
        $oExcelService->setFileName('Krsc_Example_13');

        $oExcelService->setReportView(
            $this->getReportView()->setDocumentProperties()
        );
        $oExcelService->createReport();
    }
}
