<?php
/**
 * Abstract class for creation of example reports.
 * 
 * @category KrscReports
 * @package KrscReports_Report
 * @author Krzysztof Ruszczyński <http://www.ruszczynski.eu>
 */
abstract class KrscReports_Report_ExampleReport
{
    /**
     * nazwa pola wejściowego z identyfikatorem raportu do wygenerowania
     */
    const INPUT_REPORT_ID = 'report_id';
    
    /**
     * @var array numeric table with instances of KrscReports_Report_ExampleReport
     */
    static protected $_aReports;
    
    static public function createObjects()
    {
        new KrscReports_Report_ExampleReportNoStyles();
        new KrscReports_Report_ExampleReportBasicStyles();
        new KrscReports_Report_ExampleReportManyStyles();
        new KrscReports_Report_ExampleReportManyTables();
        new KrscReports_Report_ExampleReportTableWithSums();
        new KrscReports_Report_ExampleReportVariousPlaces();
    }
    
    /**
     * Method returning array with report objects.
     * @return array numeric table with instances of KrscReports_Report_ExampleReport
     */
    static public function getReportArray()
    {
        return self::$_aReports;
    }
    
    /**
     * Method creates report from object which was stored with given on input position.
     * @param integer $iPosition position of object for generating report
     * @throws Exception thrown when requested object doesn't exist
     */
    static public function generateReport( $iPosition )
    {
        if( isset( self::$_aReports[$iPosition] ) )
        {
            self::$_aReports[$iPosition]->generate();
        }
        else
        {
            throw new Exception( 'Requested report doesn\'t exist!' );
        }
    }

    /**
     * Add newly constructed object to list of objects with reports
     * @return void
     */
    public function __construct()
    {
        self::$_aReports[] = $this;
    }
    
    /**
     * Method returns description of generated by that object worksheet.
     * @return string description of report
     */
    abstract public function getDescription();
    
    /**
     * Method responsible for creating PHPExcel object with generated report.
     * @return void
     */
    abstract public function generate();
   
}

