<?php
use KrscReports\Service;

/**
 * This file is part of KrscReports.
 *
 * Copyright (c) 2020 Krzysztof Ruszczyński
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
 *
 * @category KrscReports
 * @package KrscReports_Report
 * @copyright Copyright (c) 2020 Krzysztof Ruszczyński
 * @license http://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt	LGPL
 * @version 2.0.6, 2020-02-12
 */

/**
 * Example report creating table with 100 rows via Service.
 *
 * @category KrscReports
 * @package KrscReports_Report
 * @author Krzysztof Ruszczyński <http://www.ruszczynski.eu>
 */
class KrscReports_Report_ExampleReportManyRows extends KrscReports_Report_ExampleReport
{
    /**
     * @var integer number of rows to create
     */
    protected $_iNumberOfRows = 100;

    /**
     * Method returns description of generated by that object worksheet.
     * @return string description of report
     */
    public function getDescription()
    {
        return 'Report with one table with 100 rows (made with \KrscReports\Service).';
    }

    /**
     * Method responsible for creating service with generated report.
     * @return void
     */
    public function generate()
    {
        $excelService = new Service();
        $excelService->setSpreadsheetName('First_Spreadsheet');
        $excelService->setFileName('Krsc_Example_10');

        $dataForExcel = array();
        $iterator = 1;
        for ($i = 0; $i < $this->_iNumberOfRows; $i++) {
            $dataForExcel[] = array($iterator++, $iterator++, $iterator++);
        }

        $reportView = new \KrscReports\Views\SingleTable();
        $reportView->addOptions(array(\KrscReports\Views\AbstractView::KEY_DOCUMENT_PROPERTIES => array(), KrscReports\Views\AbstractView::KEY_USE_FROM_ARRAY => true));
        $reportView->setData(
            $dataForExcel,
            array('First column', 'Second column', 'Third column')
        );

        $reportView->setDocumentProperties();
        $excelService->setReportView($reportView);
        $excelService->createReport();
    }
}
